//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CameraSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CameraSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Camera.Resources.CameraSettings", typeof(CameraSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加过滤组.
        /// </summary>
        internal static string Button_AddFilterGroup {
            get {
                return ResourceManager.GetString("Button_AddFilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除组.
        /// </summary>
        internal static string Button_RemoveFilterGroup {
            get {
                return ResourceManager.GetString("Button_RemoveFilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存设置.
        /// </summary>
        internal static string Button_SaveSettings {
            get {
                return ResourceManager.GetString("Button_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字母.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_Alphabetic {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_Alphabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字母数字.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_AlphaNumeric {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_AlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任意字符.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_Any {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十六进制.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_Hexadecimal {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_Numeric {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可打印ASCII.
        /// </summary>
        internal static string Enum_BarcodeCharacterType_PrintableAscii {
            get {
                return ResourceManager.GetString("Enum_BarcodeCharacterType_PrintableAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符类型规则.
        /// </summary>
        internal static string Header_CharTypeRule {
            get {
                return ResourceManager.GetString("Header_CharTypeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含规则.
        /// </summary>
        internal static string Header_ContainsRule {
            get {
                return ResourceManager.GetString("Header_ContainsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义正则规则.
        /// </summary>
        internal static string Header_CustomRegexRule {
            get {
                return ResourceManager.GetString("Header_CustomRegexRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结尾规则.
        /// </summary>
        internal static string Header_EndsWithRule {
            get {
                return ResourceManager.GetString("Header_EndsWithRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度规则.
        /// </summary>
        internal static string Header_LengthRule {
            get {
                return ResourceManager.GetString("Header_LengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不包含规则.
        /// </summary>
        internal static string Header_NotContainsRule {
            get {
                return ResourceManager.GetString("Header_NotContainsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始规则.
        /// </summary>
        internal static string Header_StartsWithRule {
            get {
                return ResourceManager.GetString("Header_StartsWithRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符类型:.
        /// </summary>
        internal static string Label_CharacterType {
            get {
                return ResourceManager.GetString("Label_CharacterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间窗口 (毫秒):.
        /// </summary>
        internal static string Label_DuplicationTimeWindow {
            get {
                return ResourceManager.GetString("Label_DuplicationTimeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤数量:.
        /// </summary>
        internal static string Label_FilterCount {
            get {
                return ResourceManager.GetString("Label_FilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大长度:.
        /// </summary>
        internal static string Label_MaxLength {
            get {
                return ResourceManager.GetString("Label_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小长度:.
        /// </summary>
        internal static string Label_MinLength {
            get {
                return ResourceManager.GetString("Label_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式:.
        /// </summary>
        internal static string Label_Pattern {
            get {
                return ResourceManager.GetString("Label_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正则表达式:.
        /// </summary>
        internal static string Label_RegexPattern {
            get {
                return ResourceManager.GetString("Label_RegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规则组名称:.
        /// </summary>
        internal static string Label_RuleGroupName {
            get {
                return ResourceManager.GetString("Label_RuleGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件夹:.
        /// </summary>
        internal static string Label_SaveFolder {
            get {
                return ResourceManager.GetString("Label_SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码去重.
        /// </summary>
        internal static string TabHeader_BarcodeDuplication {
            get {
                return ResourceManager.GetString("TabHeader_BarcodeDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码过滤.
        /// </summary>
        internal static string TabHeader_BarcodeFiltering {
            get {
                return ResourceManager.GetString("TabHeader_BarcodeFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码类型.
        /// </summary>
        internal static string TabHeader_BarcodeTypes {
            get {
                return ResourceManager.GetString("TabHeader_BarcodeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像保存.
        /// </summary>
        internal static string TabHeader_ImageSaving {
            get {
                return ResourceManager.GetString("TabHeader_ImageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用条码去重过滤器.
        /// </summary>
        internal static string Toggle_EnableBarcodeDuplication {
            get {
                return ResourceManager.GetString("Toggle_EnableBarcodeDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用条码过滤.
        /// </summary>
        internal static string Toggle_EnableBarcodeFiltering {
            get {
                return ResourceManager.GetString("Toggle_EnableBarcodeFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用条码类型选择.
        /// </summary>
        internal static string Toggle_EnableBarcodeTypeSelection {
            get {
                return ResourceManager.GetString("Toggle_EnableBarcodeTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用字符类型规则.
        /// </summary>
        internal static string Toggle_EnableCharTypeRule {
            get {
                return ResourceManager.GetString("Toggle_EnableCharTypeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用包含规则.
        /// </summary>
        internal static string Toggle_EnableContainsRule {
            get {
                return ResourceManager.GetString("Toggle_EnableContainsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用自定义正则规则.
        /// </summary>
        internal static string Toggle_EnableCustomRegexRule {
            get {
                return ResourceManager.GetString("Toggle_EnableCustomRegexRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用结尾规则.
        /// </summary>
        internal static string Toggle_EnableEndsWithRule {
            get {
                return ResourceManager.GetString("Toggle_EnableEndsWithRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用图像保存.
        /// </summary>
        internal static string Toggle_EnableImageSaving {
            get {
                return ResourceManager.GetString("Toggle_EnableImageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用长度规则.
        /// </summary>
        internal static string Toggle_EnableLengthRule {
            get {
                return ResourceManager.GetString("Toggle_EnableLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用不包含规则.
        /// </summary>
        internal static string Toggle_EnableNotContainsRule {
            get {
                return ResourceManager.GetString("Toggle_EnableNotContainsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用此规则组.
        /// </summary>
        internal static string Toggle_EnableRuleGroup {
            get {
                return ResourceManager.GetString("Toggle_EnableRuleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用起始规则.
        /// </summary>
        internal static string Toggle_EnableStartsWithRule {
            get {
                return ResourceManager.GetString("Toggle_EnableStartsWithRule", resourceCulture);
            }
        }
    }
}
