//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedUI.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        internal static string BarcodeChuteSettings_BasicTitle {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_BasicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Type:.
        /// </summary>
        internal static string BarcodeChuteSettings_CharType {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_CharType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric.
        /// </summary>
        internal static string BarcodeChuteSettings_CharType_Alphanumeric {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_CharType_Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        internal static string BarcodeChuteSettings_CharType_Digit {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_CharType_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string BarcodeChuteSettings_CharType_Letter {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_CharType_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute Count:.
        /// </summary>
        internal static string BarcodeChuteSettings_ChuteCount {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_ChuteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains:.
        /// </summary>
        internal static string BarcodeChuteSettings_Contains {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter required content.
        /// </summary>
        internal static string BarcodeChuteSettings_Contains_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_Contains_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Chute:.
        /// </summary>
        internal static string BarcodeChuteSettings_CurrentChute {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_CurrentChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With:.
        /// </summary>
        internal static string BarcodeChuteSettings_EndsWith {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter end characters.
        /// </summary>
        internal static string BarcodeChuteSettings_EndsWith_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_EndsWith_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Chute:.
        /// </summary>
        internal static string BarcodeChuteSettings_ErrorChute {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_ErrorChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Range:.
        /// </summary>
        internal static string BarcodeChuteSettings_LengthRange {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_LengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoRead Chute:.
        /// </summary>
        internal static string BarcodeChuteSettings_NoReadChute {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NoReadChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Contains:.
        /// </summary>
        internal static string BarcodeChuteSettings_NotContains {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter forbidden content.
        /// </summary>
        internal static string BarcodeChuteSettings_NotContains_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotContains_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ends With:.
        /// </summary>
        internal static string BarcodeChuteSettings_NotEndsWith {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter forbidden end characters.
        /// </summary>
        internal static string BarcodeChuteSettings_NotEndsWith_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotEndsWith_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Starts With:.
        /// </summary>
        internal static string BarcodeChuteSettings_NotStartsWith {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter forbidden start characters.
        /// </summary>
        internal static string BarcodeChuteSettings_NotStartsWith_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_NotStartsWith_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Pattern:.
        /// </summary>
        internal static string BarcodeChuteSettings_RegexPattern {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_RegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter regex pattern.
        /// </summary>
        internal static string BarcodeChuteSettings_RegexPattern_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_RegexPattern_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Settings.
        /// </summary>
        internal static string BarcodeChuteSettings_RuleTitle {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_RuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With:.
        /// </summary>
        internal static string BarcodeChuteSettings_StartsWith {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter start characters.
        /// </summary>
        internal static string BarcodeChuteSettings_StartsWith_Placeholder {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_StartsWith_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Chute:.
        /// </summary>
        internal static string BarcodeChuteSettings_TimeoutChute {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_TimeoutChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute Rule Settings.
        /// </summary>
        internal static string BarcodeChuteSettings_Title {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重模块 Mismatch Chute:.
        /// </summary>
        internal static string BarcodeChuteSettings_WeightMismatchChute {
            get {
                return ResourceManager.GetString("BarcodeChuteSettings_WeightMismatchChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP.
        /// </summary>
        internal static string BMP {
            get {
                return ResourceManager.GetString("BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Filter Configuration.
        /// </summary>
        internal static string CameraSettings_BarcodeFilter_Title {
            get {
                return ResourceManager.GetString("CameraSettings_BarcodeFilter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string CameraSettings_BrowseButton {
            get {
                return ResourceManager.GetString("CameraSettings_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机模块 Selection.
        /// </summary>
        internal static string CameraSettings_CameraSelection_Title {
            get {
                return ResourceManager.GetString("CameraSettings_CameraSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机模块 Type:.
        /// </summary>
        internal static string CameraSettings_CameraTypeLabel {
            get {
                return ResourceManager.GetString("CameraSettings_CameraTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Barcode Repeat Filter.
        /// </summary>
        internal static string CameraSettings_EnableBarcodeRepeatFilter {
            get {
                return ResourceManager.GetString("CameraSettings_EnableBarcodeRepeatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Image Saving.
        /// </summary>
        internal static string CameraSettings_EnableImageSaving {
            get {
                return ResourceManager.GetString("CameraSettings_EnableImageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Format:.
        /// </summary>
        internal static string CameraSettings_ImageFormatLabel {
            get {
                return ResourceManager.GetString("CameraSettings_ImageFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Save Configuration.
        /// </summary>
        internal static string CameraSettings_ImageSave_Title {
            get {
                return ResourceManager.GetString("CameraSettings_ImageSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Path:.
        /// </summary>
        internal static string CameraSettings_ImageSavePathLabel {
            get {
                return ResourceManager.GetString("CameraSettings_ImageSavePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string CameraSettings_ManufacturerLabel {
            get {
                return ResourceManager.GetString("CameraSettings_ManufacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Count:.
        /// </summary>
        internal static string CameraSettings_RepeatCountLabel {
            get {
                return ResourceManager.GetString("CameraSettings_RepeatCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Time (ms):.
        /// </summary>
        internal static string CameraSettings_RepeatTimeLabel {
            get {
                return ResourceManager.GetString("CameraSettings_RepeatTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机模块 Settings.
        /// </summary>
        internal static string CameraSettings_Title {
            get {
                return ResourceManager.GetString("CameraSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string CarConfig_Acceleration {
            get {
                return ResourceManager.GetString("CarConfig_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Car.
        /// </summary>
        internal static string CarConfig_AddCar {
            get {
                return ResourceManager.GetString("CarConfig_AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CarConfig_Address {
            get {
                return ResourceManager.GetString("CarConfig_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string CarConfig_DefaultName {
            get {
                return ResourceManager.GetString("CarConfig_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (ms).
        /// </summary>
        internal static string CarConfig_Delay {
            get {
                return ResourceManager.GetString("CarConfig_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        internal static string CarConfig_Name {
            get {
                return ResourceManager.GetString("CarConfig_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string CarConfig_Speed {
            get {
                return ResourceManager.GetString("CarConfig_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Time (ms).
        /// </summary>
        internal static string CarConfig_Time {
            get {
                return ResourceManager.GetString("CarConfig_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Configuration.
        /// </summary>
        internal static string CarConfig_Title {
            get {
                return ResourceManager.GetString("CarConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Car.
        /// </summary>
        internal static string CarSequence_AddCarButton {
            get {
                return ResourceManager.GetString("CarSequence_AddCarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute List.
        /// </summary>
        internal static string CarSequence_ChuteListTitle {
            get {
                return ResourceManager.GetString("CarSequence_ChuteListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Sequence for Chute {0}.
        /// </summary>
        internal static string CarSequence_ChuteSequenceTitle {
            get {
                return ResourceManager.GetString("CarSequence_ChuteSequenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        internal static string CarSequence_DelayLabel {
            get {
                return ResourceManager.GetString("CarSequence_DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before sending this car command (ms).
        /// </summary>
        internal static string CarSequence_DelayTooltip {
            get {
                return ResourceManager.GetString("CarSequence_DelayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string CarSequence_Forward {
            get {
                return ResourceManager.GetString("CarSequence_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string CarSequence_MsLabel {
            get {
                return ResourceManager.GetString("CarSequence_MsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string CarSequence_Reverse {
            get {
                return ResourceManager.GetString("CarSequence_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Forward.
        /// </summary>
        internal static string CarSequence_SetForwardButton {
            get {
                return ResourceManager.GetString("CarSequence_SetForwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Reverse.
        /// </summary>
        internal static string CarSequence_SetReverseButton {
            get {
                return ResourceManager.GetString("CarSequence_SetReverseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string HikvisionSettings_IpLabel {
            get {
                return ResourceManager.GetString("HikvisionSettings_IpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string HikvisionSettings_PasswordLabel {
            get {
                return ResourceManager.GetString("HikvisionSettings_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string HikvisionSettings_PortLabel {
            get {
                return ResourceManager.GetString("HikvisionSettings_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikvision Security 相机模块 Settings.
        /// </summary>
        internal static string HikvisionSettings_Title {
            get {
                return ResourceManager.GetString("HikvisionSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string HikvisionSettings_UserLabel {
            get {
                return ResourceManager.GetString("HikvisionSettings_UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string HistoryDialog_All {
            get {
                return ResourceManager.GetString("HistoryDialog_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string HistoryDialog_Button_ExportExcel {
            get {
                return ResourceManager.GetString("HistoryDialog_Button_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string HistoryDialog_Button_Query {
            get {
                return ResourceManager.GetString("HistoryDialog_Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed: {0}.
        /// </summary>
        internal static string HistoryDialog_ExportFailedFormat {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRecords.
        /// </summary>
        internal static string HistoryDialog_ExportFileNamePrefix {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportFileNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files|*.xlsx.
        /// </summary>
        internal static string HistoryDialog_ExportFilter {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Records.
        /// </summary>
        internal static string HistoryDialog_ExportSheetName {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records exported successfully to {1}.
        /// </summary>
        internal static string HistoryDialog_ExportSuccessFormat {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Package Records.
        /// </summary>
        internal static string HistoryDialog_ExportTitle {
            get {
                return ResourceManager.GetString("HistoryDialog_ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string HistoryDialog_Header_Barcode {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute.
        /// </summary>
        internal static string HistoryDialog_Header_Chute {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Chute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        internal static string HistoryDialog_Header_CreateTime {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height(cm).
        /// </summary>
        internal static string HistoryDialog_Header_Height {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string HistoryDialog_Header_Id {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string HistoryDialog_Header_Image {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length(cm).
        /// </summary>
        internal static string HistoryDialog_Header_Length {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string HistoryDialog_Header_Remarks {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HistoryDialog_Header_Status {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume(cm³).
        /// </summary>
        internal static string HistoryDialog_Header_Volume {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重模块(kg).
        /// </summary>
        internal static string HistoryDialog_Header_Weight {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width(cm).
        /// </summary>
        internal static string HistoryDialog_Header_Width {
            get {
                return ResourceManager.GetString("HistoryDialog_Header_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file not found: {0}.
        /// </summary>
        internal static string HistoryDialog_ImageNotFoundFormat {
            get {
                return ResourceManager.GetString("HistoryDialog_ImageNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open image: {0}.
        /// </summary>
        internal static string HistoryDialog_ImageOpenFailedFormat {
            get {
                return ResourceManager.GetString("HistoryDialog_ImageOpenFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode:.
        /// </summary>
        internal static string HistoryDialog_Label_Barcode {
            get {
                return ResourceManager.GetString("HistoryDialog_Label_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute:.
        /// </summary>
        internal static string HistoryDialog_Label_Chute {
            get {
                return ResourceManager.GetString("HistoryDialog_Label_Chute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string HistoryDialog_Label_EndDate {
            get {
                return ResourceManager.GetString("HistoryDialog_Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string HistoryDialog_Label_StartDate {
            get {
                return ResourceManager.GetString("HistoryDialog_Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string HistoryDialog_Label_Status {
            get {
                return ResourceManager.GetString("HistoryDialog_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter barcode....
        /// </summary>
        internal static string HistoryDialog_Placeholder_Barcode {
            get {
                return ResourceManager.GetString("HistoryDialog_Placeholder_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chute number....
        /// </summary>
        internal static string HistoryDialog_Placeholder_Chute {
            get {
                return ResourceManager.GetString("HistoryDialog_Placeholder_Chute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query failed.
        /// </summary>
        internal static string HistoryDialog_QueryFailed {
            get {
                return ResourceManager.GetString("HistoryDialog_QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query successful.
        /// </summary>
        internal static string HistoryDialog_QuerySuccess {
            get {
                return ResourceManager.GetString("HistoryDialog_QuerySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string HistoryDialog_Status_Created {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HistoryDialog_Status_Error {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string HistoryDialog_Status_Failed {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Rejected.
        /// </summary>
        internal static string HistoryDialog_Status_LoadingRejected {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_LoadingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Success.
        /// </summary>
        internal static string HistoryDialog_Status_LoadingSuccess {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_LoadingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Timeout.
        /// </summary>
        internal static string HistoryDialog_Status_LoadingTimeout {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_LoadingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string HistoryDialog_Status_Offline {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string HistoryDialog_Status_Success {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string HistoryDialog_Status_Timeout {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Loading.
        /// </summary>
        internal static string HistoryDialog_Status_WaitingForLoading {
            get {
                return ResourceManager.GetString("HistoryDialog_Status_WaitingForLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string HistoryDialog_Tooltip_OpenImage {
            get {
                return ResourceManager.GetString("HistoryDialog_Tooltip_OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG.
        /// </summary>
        internal static string JPEG {
            get {
                return ResourceManager.GetString("JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Address:.
        /// </summary>
        internal static string ModulesTcpSettings_Label_Address {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Chute:.
        /// </summary>
        internal static string ModulesTcpSettings_Label_ExceptionChute {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Label_ExceptionChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Time (ms):.
        /// </summary>
        internal static string ModulesTcpSettings_Label_MaxTime {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Label_MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Time (ms):.
        /// </summary>
        internal static string ModulesTcpSettings_Label_MinTime {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Label_MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string ModulesTcpSettings_Label_Port {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter TCP Address.
        /// </summary>
        internal static string ModulesTcpSettings_Placeholder_Address {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Placeholder_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Exception Chute.
        /// </summary>
        internal static string ModulesTcpSettings_Placeholder_ExceptionChute {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Placeholder_ExceptionChute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Max Time.
        /// </summary>
        internal static string ModulesTcpSettings_Placeholder_MaxTime {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Placeholder_MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Min Time.
        /// </summary>
        internal static string ModulesTcpSettings_Placeholder_MinTime {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Placeholder_MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Port.
        /// </summary>
        internal static string ModulesTcpSettings_Placeholder_Port {
            get {
                return ResourceManager.GetString("ModulesTcpSettings_Placeholder_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        internal static string PNG {
            get {
                return ResourceManager.GetString("PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP.
        /// </summary>
        internal static string TCP {
            get {
                return ResourceManager.GetString("TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP 相机模块.
        /// </summary>
        internal static string TCP相机 {
            get {
                return ResourceManager.GetString("TCP相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF.
        /// </summary>
        internal static string TIFF {
            get {
                return ResourceManager.GetString("TIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate:.
        /// </summary>
        internal static string WeightSettings_BaudRate {
            get {
                return ResourceManager.GetString("WeightSettings_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits:.
        /// </summary>
        internal static string WeightSettings_DataBits {
            get {
                return ResourceManager.GetString("WeightSettings_DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 称重模块 Fusion.
        /// </summary>
        internal static string WeightSettings_EnableFusion {
            get {
                return ResourceManager.GetString("WeightSettings_EnableFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重模块 Fusion Settings.
        /// </summary>
        internal static string WeightSettings_FusionTitle {
            get {
                return ResourceManager.GetString("WeightSettings_FusionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 称重模块:.
        /// </summary>
        internal static string WeightSettings_MinWeight {
            get {
                return ResourceManager.GetString("WeightSettings_MinWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter minimum weight.
        /// </summary>
        internal static string WeightSettings_MinWeight_Placeholder {
            get {
                return ResourceManager.GetString("WeightSettings_MinWeight_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the minimum threshold for weight detection (g).
        /// </summary>
        internal static string WeightSettings_MinWeight_Tooltip {
            get {
                return ResourceManager.GetString("WeightSettings_MinWeight_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity:.
        /// </summary>
        internal static string WeightSettings_Parity {
            get {
                return ResourceManager.GetString("WeightSettings_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Name:.
        /// </summary>
        internal static string WeightSettings_PortName {
            get {
                return ResourceManager.GetString("WeightSettings_PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string WeightSettings_Refresh {
            get {
                return ResourceManager.GetString("WeightSettings_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh available ports.
        /// </summary>
        internal static string WeightSettings_Refresh_Tooltip {
            get {
                return ResourceManager.GetString("WeightSettings_Refresh_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Count:.
        /// </summary>
        internal static string WeightSettings_SampleCount {
            get {
                return ResourceManager.GetString("WeightSettings_SampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sample count (3-10).
        /// </summary>
        internal static string WeightSettings_SampleCount_Placeholder {
            get {
                return ResourceManager.GetString("WeightSettings_SampleCount_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of samples required for stability check, range 3-10.
        /// </summary>
        internal static string WeightSettings_SampleCount_Tooltip {
            get {
                return ResourceManager.GetString("WeightSettings_SampleCount_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Settings.
        /// </summary>
        internal static string WeightSettings_SerialTitle {
            get {
                return ResourceManager.GetString("WeightSettings_SerialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bits:.
        /// </summary>
        internal static string WeightSettings_StopBits {
            get {
                return ResourceManager.GetString("WeightSettings_StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range:.
        /// </summary>
        internal static string WeightSettings_TimeRange {
            get {
                return ResourceManager.GetString("WeightSettings_TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Time.
        /// </summary>
        internal static string WeightSettings_TimeRange_Lower_Placeholder {
            get {
                return ResourceManager.GetString("WeightSettings_TimeRange_Lower_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Time.
        /// </summary>
        internal static string WeightSettings_TimeRange_Upper_Placeholder {
            get {
                return ResourceManager.GetString("WeightSettings_TimeRange_Upper_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range Settings.
        /// </summary>
        internal static string WeightSettings_TimeRangeTitle {
            get {
                return ResourceManager.GetString("WeightSettings_TimeRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重模块 Settings.
        /// </summary>
        internal static string WeightSettings_Title {
            get {
                return ResourceManager.GetString("WeightSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string WeightSettings_Unit_Gram {
            get {
                return ResourceManager.GetString("WeightSettings_Unit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string WeightSettings_Unit_Millisecond {
            get {
                return ResourceManager.GetString("WeightSettings_Unit_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重模块 Type:.
        /// </summary>
        internal static string WeightSettings_WeightType {
            get {
                return ResourceManager.GetString("WeightSettings_WeightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuaRay.
        /// </summary>
        internal static string 华睿 {
            get {
                return ResourceManager.GetString("华睿", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial 相机模块.
        /// </summary>
        internal static string 工业相机 {
            get {
                return ResourceManager.GetString("工业相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart 相机模块.
        /// </summary>
        internal static string 智能相机 {
            get {
                return ResourceManager.GetString("智能相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikvision.
        /// </summary>
        internal static string 海康 {
            get {
                return ResourceManager.GetString("海康", resourceCulture);
            }
        }
    }
}
