//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChileSowing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChileSowing.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        internal static string Button_History {
            get {
                return ResourceManager.GetString("Button_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格口监控.
        /// </summary>
        internal static string Label_ChuteMonitoring {
            get {
                return ResourceManager.GetString("Label_ChuteMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包裹信息.
        /// </summary>
        internal static string Label_PackageInfo {
            get {
                return ResourceManager.GetString("Label_PackageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描商品SKU.
        /// </summary>
        internal static string Label_ScanProductSku {
            get {
                return ResourceManager.GetString("Label_ScanProductSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描波次号.
        /// </summary>
        internal static string Label_ScanWaveNumber {
            get {
                return ResourceManager.GetString("Label_ScanWaveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计信息.
        /// </summary>
        internal static string Label_Statistics {
            get {
                return ResourceManager.GetString("Label_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请扫描或输入SKU码.
        /// </summary>
        internal static string Placeholder_EnterScanSku {
            get {
                return ResourceManager.GetString("Placeholder_EnterScanSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请扫描或输入波次号.
        /// </summary>
        internal static string Placeholder_EnterScanWaveNumber {
            get {
                return ResourceManager.GetString("Placeholder_EnterScanWaveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格口规则设置.
        /// </summary>
        internal static string Settings_ChuteRule {
            get {
                return ResourceManager.GetString("Settings_ChuteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韵达快手接口.
        /// </summary>
        internal static string Settings_KuaiShou {
            get {
                return ResourceManager.GetString("Settings_KuaiShou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus TCP.
        /// </summary>
        internal static string Settings_ModbusTcp {
            get {
                return ResourceManager.GetString("Settings_ModbusTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string Status_CPU {
            get {
                return ResourceManager.GetString("Status_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内存.
        /// </summary>
        internal static string Status_Memory {
            get {
                return ResourceManager.GetString("Status_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行时间.
        /// </summary>
        internal static string Status_Uptime {
            get {
                return ResourceManager.GetString("Status_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看历史记录.
        /// </summary>
        internal static string Tooltip_History {
            get {
                return ResourceManager.GetString("Tooltip_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开设置.
        /// </summary>
        internal static string Tooltip_Settings {
            get {
                return ResourceManager.GetString("Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播种墙系统.
        /// </summary>
        internal static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
