//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorting_Car.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorting_Car.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小车 {0}.
        /// </summary>
        internal static string CarConfig_NewCarNameFormat {
            get {
                return ResourceManager.GetString("CarConfig_NewCarNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格口 {0} 序列.
        /// </summary>
        internal static string CarSequence_ChuteSequenceTitle {
            get {
                return ResourceManager.GetString("CarSequence_ChuteSequenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率.
        /// </summary>
        internal static string CarSerialPortSettings_BaudRate {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据位.
        /// </summary>
        internal static string CarSerialPortSettings_DataBits {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验位.
        /// </summary>
        internal static string CarSerialPortSettings_Parity {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口名称.
        /// </summary>
        internal static string CarSerialPortSettings_PortName {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止位.
        /// </summary>
        internal static string CarSerialPortSettings_StopBits {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小车串口设置.
        /// </summary>
        internal static string CarSerialPortSettings_Title {
            get {
                return ResourceManager.GetString("CarSerialPortSettings_Title", resourceCulture);
            }
        }
    }
}
